### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by huoji120** [tandasat/SimpleSvmHook#3]
hi, do you have any suggestions how to improve the performance?
it make me very lag even on a real computer
i think its VM exits make lag, any idea?

**Comment by tandasat** [comment]
You should be able to improve performance with a way described in the issue #1. This reduces frequency of #VMEXIT. 

Also, you should be able to speed up the #VMEXIT that switches permissions of pages by preparing other set of NTPs and switching between two by updating `N_CR3`, instead of flipping bits within the same NTP. I have not implemented this idea but it is something you should look into.

**Comment by BomboBombone** [comment]
tandasat a real one
